### PR TITLE
Fix: do not split "New to Sqitch?" link

### PR DESCRIPTION
**Pull request by pau4o**
On narrow screens it looks visually broken as it goes on two rows.

With new rule it will remain button like form and move it onto new row as a whole.

screenshot

### CODE REVIEW

**Comment by theory** [comment]
LOL, I didnt' see that on iOS. Wild. Maybe it should just be done for the text of all buttons in `#hi`?

**Comment by pau4o** [comment]
> LOL, I didnt' see that on iOS. Wild. Maybe it should just be done for the text of all buttons in `#hi`?

Yep, I was thinking of this, but choose to be more conservative as I didn't check all pages. To target all links in `#hi` we can simplify selector to:

```css
#hi a {
    white-space: nowrap;
}
```

**Comment by theory** [comment]
Perfect, `#hi` is only on the home page, so let's do that.

**Comment by pau4o** [comment]
@theory selector is changed in second commit.

**Pull request merged**
