### PR TITLE
Fix minor typos in docs/_index.md

### PR DESCRIPTION
**Pull request by swagile1**

### CODE REVIEW

**Review by autarch — APPROVED** [review]

**Comment by theory** [comment]
Thank you!

**Comment by theory** [comment]
Oh @autarch, merges should go into the develop branch. Master is just for releases.

**Comment by autarch** [comment]
Doh, I'm sorry. I think we can fix this for the future but we'd need a permanent `develop` branch (I don't see one in the repo right now). Then we can change the default branch in GitHub, so that's what people get by default for PRs.

**Comment by theory** [comment]
Wait, no, I’m sorry, I thought this was the sqitch repo, which has that pattern. Sqitch.org does not. Please ignore me.

**Comment by theory** [comment]
I published these fixes in f4ca7bf.

**Comment by theory** [comment]
Er, make that sqitchers/sqitchers.github.io#34bab53.

**Pull request merged**
